### ISSUE TITLE
hover effect and anchor tag in footer section

### ISSUE THREAD

**Issue by abhishek12raj** [SineshX/PrabhawatiVidyaPeeth#15]
![12](https://user-images.githubusercontent.com/99470924/194579017-05383bb1-f0cc-4977-bff7-8353dc429612.png)

![4](https://user-images.githubusercontent.com/99470924/194590048-31b1df30-b1f4-4a23-860f-2afbef8063d8.png)
add hover effect on this
@SineshX  can i work on this issue?

**Comment by SineshX** [comment]
that's a great idea, kindly chose right color for it. 

I'll assign it to you.
