### ISSUE TITLE
Improve the UI of the header section

### ISSUE THREAD

**Issue by surya-doc** [SineshX/PrabhawatiVidyaPeeth#17]
![image](https://user-images.githubusercontent.com/69008196/194584814-b716a047-fde9-49fe-94f1-536420606c2c.png)
* In the header the logo is too big which creates unnecessary blank places. Want to work in this issue.

**Comment by SineshX** [comment]
thank you for the suggestion; that issue has been resolved now; kindly check. [https://sineshx.com/PrabhawatiVidyaPeeth/](https://prabhawatividyapeeth.in/)
