### ISSUE TITLE
Navbar style enhance

### ISSUE THREAD

**Issue by RishabhJain0721** [SineshX/PrabhawatiVidyaPeeth#25]
![Screenshot 2022-10-07 235747](https://user-images.githubusercontent.com/107767172/194625477-52744670-dbf9-44a0-ab29-86af2c91d4a2.png)
### Hi
The right part of navbar seems to be a little crowded.Moreover the hover effects of buttons are not looking very good.
I would like to fix this issue.Please assign me this task.

**Comment by RishabhJain0721** [comment]
@SineshX Please review my PR.

**Comment by SineshX** [comment]
Sure ..
