### ISSUE TITLE
Designing the error 404 page for the website.

### ISSUE THREAD

**Issue by Pushkar03** [SineshX/PrabhawatiVidyaPeeth#27]
I can contribute by providing a complete UI design of the error 404 page. Kindly assign me this issue !

**Comment by Pushkar03** [comment]
### **Added the designs in both Web and App mode.**

_Website View_
![Desktop version](https://user-images.githubusercontent.com/81770626/194637621-24dab514-efde-4ffa-9ef8-cc05e62d6f1b.png)

_App View_
![iPhone 14](https://user-images.githubusercontent.com/81770626/194637644-823de590-cf85-434a-a10f-bb3b9558e7fa.png)

**Comment by SineshX** [comment]
looks awesome. 
Kindly PR.
thanks for your time and efforts.

**Comment by Pushkar03** [comment]
Thanks !
I have made a PR regarding the same kindly take a look.
