### ISSUE TITLE
Optimize the images and improve their naming in the project

### ISSUE THREAD

**Issue by BrunoLagoa** [SineshX/PrabhawatiVidyaPeeth#28]
Improve file names

![Captura de Tela 2022-10-07 às 16 10 57](https://user-images.githubusercontent.com/3878945/194636920-62a79fb5-36ab-4986-88b4-d9e47158ab0c.png)

Improve performance with image optimization
![Captura de Tela 2022-10-07 às 16 13 40](https://user-images.githubusercontent.com/3878945/194637276-4d6bd4ab-7de8-4c69-b3bd-32be99812bc4.png)
![Captura de Tela 2022-10-07 às 16 13 49](https://user-images.githubusercontent.com/3878945/194637278-0fff7d01-e1cb-45ad-9bca-e36c86d3607d.png)

If you think it's fair, you can assign this adjustment on my behalf.

**Comment by SineshX** [comment]
ya sure @BrunoLagoa

**Comment by BrunoLagoa** [comment]
Thanks for assigning the task on my behalf, I made the adjustment and created the pr.
