### ISSUE TITLE
Improve navbar

### ISSUE THREAD

**Issue by abhishek12raj** [SineshX/PrabhawatiVidyaPeeth#4]
![IMG_20221007_103300](https://user-images.githubusercontent.com/99470924/194471732-02965b77-70dc-46b9-80d9-a9cd8a00ceee.jpg)
 

@SineshX can I work on this?

**Comment by aparna03dubey** [comment]
Hello @SineshX 
Can you assign this to me?

**Comment by SineshX** [comment]
ya sure @abhishek12raj and @aparna03dubey

**Comment by sakshisangaonkar** [comment]
Hi please assign me this issues.

**Comment by SineshX** [comment]
Kindly check new issue regarding navbar https://github.com/SineshX/PrabhawatiVidyaPeeth/issues/12
