### ISSUE TITLE
Navbar improvements

### ISSUE THREAD

**Issue by ArnavGuptaaa** [SineshX/PrabhawatiVidyaPeeth#9]
The following enhancements can be made: 
- Logo size must be made proportionate
- Clicking Nav links must scroll to their respective sections
- Use telephone links for telephone number
- Add a telephone icon

![image](https://user-images.githubusercontent.com/67139196/194530010-349d8611-98ce-4099-aff6-db74ec1653ee.png)

**Comment by ArnavGuptaaa** [comment]
Assign me this issue and label it for `hacktoberfest`

**Comment by SineshX** [comment]
@ArnavGuptaaa sure ... But before contribution, kindly refer the main branch coz there have been some improvement by other users. 
https://sineshx.com/PrabhawatiVidyaPeeth/

Happy Hacking , 
Thanks for your time and efforts.

**Comment by ArnavGuptaaa** [comment]
@SineshX  why was my pull request not accepted?

**Comment by SineshX** [comment]
Great work @ArnavGuptaaa ,

Please let me know if you can make it more responsive. 
![image](https://user-images.githubusercontent.com/48027382/194555145-27f23320-aed0-4ae6-b03d-aabee0c7103b.png)
